CREATE DATABASE PLATFORM_GAME;

USE PLATFORM_GAME;

CREATE TABLE Usuario(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(120) NOT NULL,
    password VARCHAR(120) NOT NULL,
    data_nascimento DATE NOT NULL,
    data_cadastro TIMESTAMP NOT NULL,
    CFP VARCHAR(15) NOT NULL,
    estudio VARCHAR(120),
    descricao VARCHAR(150),
    tipo VARCHAR(120)
);

CREATE TABLE Jogo(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(120) NOT NULL,
    password VARCHAR(120) NOT NULL,
    descricao TEXT NOT NULL,
    preco DECIMAL(7,2) NOT NULL,
    thumb_url VARCHAR(15) NOT NULL,
	dowload_url VARCHAR(120) NOT NULL,
    id_desenvolvedor INT NULL,
	CONSTRAINT FK_Desenvolvedor FOREIGN KEY (id_desenvolvedor) REFERENCES Usuario(id)
);

CREATE TABLE Dispositivo (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
titulo VARCHAR(60)
);

CREATE TABLE Jogo_Dispositivo (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
id_Jogo INT NOT NULL,
CONSTRAINT FK_ID_Jogo FOREIGN KEY (id_Jogo) REFERENCES Jogo(id),
CONSTRAINT FK_ID_Dispositivo FOREIGN KEY (id_Jogo) REFERENCES Dispositivo(id)
);

CREATE TABLE Biblioteca (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
id_Usuario INT NOT NULL,
id_Jogo INT NOT NULL,
CONSTRAINT FK_Jogo FOREIGN KEY (id_Jogo) REFERENCES Jogo(id),
CONSTRAINT FK_Usuario FOREIGN KEY (id_Usuario) REFERENCES Usuario(id)
);